
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow {
    private global::Gtk.VBox vbox3;
    
    private global::Gtk.HBox hbox2;
    
    private global::Gtk.Label label6;
    
    private global::Gtk.Entry txtUserID;
    
    private global::Gtk.Label label7;
    
    private global::Gtk.Entry txtApiKey;
    
    private global::Gtk.Button button1;
    
    private global::Gtk.Notebook notebook1;
    
    private global::Gtk.VBox vbox1;
    
    private global::Gtk.Frame frame1;
    
    private global::Gtk.Alignment GtkAlignment1;
    
    private global::Gtk.VBox vbox2;
    
    private global::Gtk.Label lblCreated;
    
    private global::Gtk.Label lblPaidUntil;
    
    private global::Gtk.Label lblLogonTimes;
    
    private global::Gtk.Label lblMinutesPlayed;
    
    private global::Gtk.Label GtkLabel1;
    
    private global::Gtk.Frame frame2;
    
    private global::Gtk.Alignment GtkAlignment2;
    
    private global::Gtk.TreeView trvCharacters;
    
    private global::Gtk.Label GtkLabel2;
    
    private global::Gtk.Label label1;
    
    protected virtual void Build() {
        global::Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((global::Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(3));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox3 = new global::Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox2 = new global::Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label6 = new global::Gtk.Label();
        this.label6.Name = "label6";
        this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("User ID:");
        this.hbox2.Add(this.label6);
        global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label6]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.txtUserID = new global::Gtk.Entry();
        this.txtUserID.CanFocus = true;
        this.txtUserID.Name = "txtUserID";
        this.txtUserID.Text = global::Mono.Unix.Catalog.GetString("1320669");
        this.txtUserID.IsEditable = true;
        this.txtUserID.InvisibleChar = '●';
        this.hbox2.Add(this.txtUserID);
        global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtUserID]));
        w2.Position = 1;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label7 = new global::Gtk.Label();
        this.label7.Name = "label7";
        this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("API Key:");
        this.hbox2.Add(this.label7);
        global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label7]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.txtApiKey = new global::Gtk.Entry();
        this.txtApiKey.CanFocus = true;
        this.txtApiKey.Name = "txtApiKey";
        this.txtApiKey.Text = global::Mono.Unix.Catalog.GetString("7D716o9mZ57EHrLt3hX0AaTMAIOw9XJ7DVzyzBufk1rbxEXsq9l5y3TUP6v5zuzg");
        this.txtApiKey.IsEditable = true;
        this.txtApiKey.InvisibleChar = '●';
        this.hbox2.Add(this.txtApiKey);
        global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtApiKey]));
        w4.Position = 3;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button1 = new global::Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseStock = true;
        this.button1.UseUnderline = true;
        this.button1.Label = "gtk-ok";
        this.hbox2.Add(this.button1);
        global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button1]));
        w5.PackType = ((global::Gtk.PackType)(1));
        w5.Position = 4;
        w5.Expand = false;
        w5.Fill = false;
        this.vbox3.Add(this.hbox2);
        global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
        w6.Position = 0;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.notebook1 = new global::Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 0;
        this.notebook1.BorderWidth = ((uint)(3));
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.vbox1 = new global::Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        this.vbox1.BorderWidth = ((uint)(2));
        // Container child vbox1.Gtk.Box+BoxChild
        this.frame1 = new global::Gtk.Frame();
        this.frame1.Name = "frame1";
        // Container child frame1.Gtk.Container+ContainerChild
        this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment1.Name = "GtkAlignment1";
        this.GtkAlignment1.LeftPadding = ((uint)(3));
        this.GtkAlignment1.TopPadding = ((uint)(3));
        this.GtkAlignment1.RightPadding = ((uint)(3));
        this.GtkAlignment1.BottomPadding = ((uint)(3));
        // Container child GtkAlignment1.Gtk.Container+ContainerChild
        this.vbox2 = new global::Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.lblCreated = new global::Gtk.Label();
        this.lblCreated.Name = "lblCreated";
        this.lblCreated.Xalign = 0F;
        this.lblCreated.LabelProp = global::Mono.Unix.Catalog.GetString("Created On:");
        this.vbox2.Add(this.lblCreated);
        global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblCreated]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.lblPaidUntil = new global::Gtk.Label();
        this.lblPaidUntil.Name = "lblPaidUntil";
        this.lblPaidUntil.Xalign = 0F;
        this.lblPaidUntil.LabelProp = global::Mono.Unix.Catalog.GetString("Paid Until:");
        this.vbox2.Add(this.lblPaidUntil);
        global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblPaidUntil]));
        w8.Position = 1;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.lblLogonTimes = new global::Gtk.Label();
        this.lblLogonTimes.Name = "lblLogonTimes";
        this.lblLogonTimes.Xalign = 0F;
        this.lblLogonTimes.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Logins:");
        this.vbox2.Add(this.lblLogonTimes);
        global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblLogonTimes]));
        w9.Position = 2;
        w9.Expand = false;
        w9.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.lblMinutesPlayed = new global::Gtk.Label();
        this.lblMinutesPlayed.Name = "lblMinutesPlayed";
        this.lblMinutesPlayed.Xalign = 0F;
        this.lblMinutesPlayed.LabelProp = global::Mono.Unix.Catalog.GetString("Number of minutes played:");
        this.vbox2.Add(this.lblMinutesPlayed);
        global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblMinutesPlayed]));
        w10.Position = 3;
        w10.Expand = false;
        w10.Fill = false;
        this.GtkAlignment1.Add(this.vbox2);
        this.frame1.Add(this.GtkAlignment1);
        this.GtkLabel1 = new global::Gtk.Label();
        this.GtkLabel1.Name = "GtkLabel1";
        this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Account Status");
        this.GtkLabel1.UseMarkup = true;
        this.frame1.LabelWidget = this.GtkLabel1;
        this.vbox1.Add(this.frame1);
        global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
        w13.Position = 0;
        w13.Expand = false;
        w13.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.frame2 = new global::Gtk.Frame();
        this.frame2.Name = "frame2";
        // Container child frame2.Gtk.Container+ContainerChild
        this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment2.Name = "GtkAlignment2";
        this.GtkAlignment2.LeftPadding = ((uint)(3));
        this.GtkAlignment2.TopPadding = ((uint)(3));
        this.GtkAlignment2.RightPadding = ((uint)(3));
        this.GtkAlignment2.BottomPadding = ((uint)(3));
        // Container child GtkAlignment2.Gtk.Container+ContainerChild
        this.trvCharacters = new global::Gtk.TreeView();
        this.trvCharacters.HeightRequest = 100;
        this.trvCharacters.CanFocus = true;
        this.trvCharacters.Name = "trvCharacters";
        this.GtkAlignment2.Add(this.trvCharacters);
        this.frame2.Add(this.GtkAlignment2);
        this.GtkLabel2 = new global::Gtk.Label();
        this.GtkLabel2.Name = "GtkLabel2";
        this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Characters");
        this.GtkLabel2.UseMarkup = true;
        this.frame2.LabelWidget = this.GtkLabel2;
        this.vbox1.Add(this.frame2);
        global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
        w16.Position = 1;
        this.notebook1.Add(this.vbox1);
        // Notebook tab
        this.label1 = new global::Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Account");
        this.notebook1.SetTabLabel(this.vbox1, this.label1);
        this.label1.ShowAll();
        this.vbox3.Add(this.notebook1);
        global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.notebook1]));
        w18.Position = 1;
        this.Add(this.vbox3);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 472;
        this.DefaultHeight = 328;
        this.Show();
        this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
