
// This file has been generated by the GUI designer. Do not modify.
namespace ECMGTK
{
	public partial class ViewItemDetails
	{
		private global::Gtk.Notebook ntbItems;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ECMGTK.ViewItemDetails
			this.Name = "ECMGTK.ViewItemDetails";
			this.Title = global::Mono.Unix.Catalog.GetString ("ViewItemDetails");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ECMGTK.ViewItemDetails.Gtk.Container+ContainerChild
			this.ntbItems = new global::Gtk.Notebook ();
			this.ntbItems.CanFocus = true;
			this.ntbItems.Name = "ntbItems";
			this.ntbItems.CurrentPage = -1;
			this.ntbItems.Scrollable = true;
			this.ntbItems.BorderWidth = ((uint)(3));
			this.Add (this.ntbItems);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 314;
			this.DefaultHeight = 300;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDelete);
		}
	}
}
