
// This file has been generated by the GUI designer. Do not modify.
namespace ECMGTK
{
	public partial class ViewItemRender
	{
		private global::Gtk.Image imgItemRender;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ECMGTK.ViewItemRender
			this.Name = "ECMGTK.ViewItemRender";
			this.Title = global::Mono.Unix.Catalog.GetString ("ViewItemRender");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ECMGTK.ViewItemRender.Gtk.Container+ContainerChild
			this.imgItemRender = new global::Gtk.Image ();
			this.imgItemRender.WidthRequest = 512;
			this.imgItemRender.HeightRequest = 512;
			this.imgItemRender.Name = "imgItemRender";
			this.Add (this.imgItemRender);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 512;
			this.DefaultHeight = 512;
			this.Show ();
		}
	}
}
