
// This file has been generated by the GUI designer. Do not modify.
namespace ECMGTK {
    public partial class AddApiKey {
        private global::Gtk.VBox vbox2;
        
        private global::Gtk.Frame frame1;
        
        private global::Gtk.Alignment GtkAlignment2;
        
        private global::Gtk.Label label2;
        
        private global::Gtk.Label GtkLabel2;
        
        private global::Gtk.Table table1;
        
        private global::Gtk.Label label3;
        
        private global::Gtk.Label label4;
        
        private global::Gtk.Entry txtApiKeyID;
        
        private global::Gtk.Entry txtVerificationCode;
        
        private global::Gtk.HButtonBox hbuttonbox2;
        
        private global::Gtk.Button btnRetrieveApi;
        
        private global::Gtk.HSeparator hseparator1;
        
        private global::Gtk.Frame frame2;
        
        private global::Gtk.Alignment GtkAlignment3;
        
        private global::Gtk.Table table2;
        
        private global::Gtk.Label GtkLabel3;
        
        private global::Gtk.Frame frame8;
        
        private global::Gtk.Alignment GtkAlignment9;
        
        private global::Gtk.TreeView trvCharacters;
        
        private global::Gtk.Label GtkLabel10;
        
        private global::Gtk.Button buttonCancel;
        
        private global::Gtk.Button button47;
        
        protected virtual void Build() {
            global::Stetic.Gui.Initialize(this);
            // Widget ECMGTK.AddApiKey
            this.WidthRequest = 400;
            this.Name = "ECMGTK.AddApiKey";
            this.Title = global::Mono.Unix.Catalog.GetString("Add new Api Key");
            this.WindowPosition = ((global::Gtk.WindowPosition)(1));
            this.Modal = true;
            this.BorderWidth = ((uint)(3));
            this.Resizable = false;
            this.AllowGrow = false;
            this.DestroyWithParent = true;
            // Internal child ECMGTK.AddApiKey.VBox
            global::Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new global::Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new global::Gtk.Frame();
            this.frame1.Name = "frame1";
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(3));
            this.GtkAlignment2.TopPadding = ((uint)(3));
            this.GtkAlignment2.RightPadding = ((uint)(3));
            this.GtkAlignment2.BottomPadding = ((uint)(3));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.label2 = new global::Gtk.Label();
            this.label2.WidthRequest = 365;
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Go to https://support.eveonline.com/api/ or click here to generate a key.\n\nClicki" +
                    "ng here will suggest a key to use all features available in this program.");
            this.label2.Wrap = true;
            this.GtkAlignment2.Add(this.label2);
            this.frame1.Add(this.GtkAlignment2);
            this.GtkLabel2 = new global::Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Need a key?");
            this.GtkLabel2.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel2;
            this.vbox2.Add(this.frame1);
            global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new global::Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 1F;
            this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Api Key ID:");
            this.table1.Add(this.label3);
            global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
            w5.XOptions = ((global::Gtk.AttachOptions)(4));
            w5.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new global::Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Verification Code:");
            this.table1.Add(this.label4);
            global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.XOptions = ((global::Gtk.AttachOptions)(4));
            w6.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtApiKeyID = new global::Gtk.Entry();
            this.txtApiKeyID.CanFocus = true;
            this.txtApiKeyID.Name = "txtApiKeyID";
            this.txtApiKeyID.Text = global::Mono.Unix.Catalog.GetString("1512");
            this.txtApiKeyID.IsEditable = true;
            this.txtApiKeyID.InvisibleChar = '●';
            this.table1.Add(this.txtApiKeyID);
            global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.txtApiKeyID]));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtVerificationCode = new global::Gtk.Entry();
            this.txtVerificationCode.CanFocus = true;
            this.txtVerificationCode.Name = "txtVerificationCode";
            this.txtVerificationCode.Text = global::Mono.Unix.Catalog.GetString("lE8EhrpxATliHxof1oiTOORFtty8jVqBdjkkFvscIYgD9mLHxK1m5z4ZvfsG0qyG");
            this.txtVerificationCode.IsEditable = true;
            this.txtVerificationCode.InvisibleChar = '●';
            this.table1.Add(this.txtVerificationCode);
            global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.txtVerificationCode]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((global::Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox2 = new global::Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.btnRetrieveApi = new global::Gtk.Button();
            this.btnRetrieveApi.CanFocus = true;
            this.btnRetrieveApi.Name = "btnRetrieveApi";
            this.btnRetrieveApi.UseUnderline = true;
            this.btnRetrieveApi.Label = global::Mono.Unix.Catalog.GetString("Retrieve Key Details");
            this.hbuttonbox2.Add(this.btnRetrieveApi);
            global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnRetrieveApi]));
            w10.Expand = false;
            w10.Fill = false;
            this.vbox2.Add(this.hbuttonbox2);
            global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator1 = new global::Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox2.Add(this.hseparator1);
            global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
            w12.Position = 3;
            w12.Expand = false;
            w12.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame2 = new global::Gtk.Frame();
            this.frame2.Name = "frame2";
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(3));
            this.GtkAlignment3.TopPadding = ((uint)(3));
            this.GtkAlignment3.RightPadding = ((uint)(3));
            this.GtkAlignment3.BottomPadding = ((uint)(3));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.GtkAlignment3.Add(this.table2);
            this.frame2.Add(this.GtkAlignment3);
            this.GtkLabel3 = new global::Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("Key Allows:");
            this.GtkLabel3.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel3;
            this.vbox2.Add(this.frame2);
            global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
            w15.Position = 4;
            w1.Add(this.vbox2);
            global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
            w16.Position = 0;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.frame8 = new global::Gtk.Frame();
            this.frame8.Name = "frame8";
            // Container child frame8.Gtk.Container+ContainerChild
            this.GtkAlignment9 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment9.Name = "GtkAlignment9";
            this.GtkAlignment9.LeftPadding = ((uint)(3));
            this.GtkAlignment9.TopPadding = ((uint)(3));
            this.GtkAlignment9.RightPadding = ((uint)(3));
            this.GtkAlignment9.BottomPadding = ((uint)(3));
            // Container child GtkAlignment9.Gtk.Container+ContainerChild
            this.trvCharacters = new global::Gtk.TreeView();
            this.trvCharacters.HeightRequest = 100;
            this.trvCharacters.CanFocus = true;
            this.trvCharacters.Name = "trvCharacters";
            this.GtkAlignment9.Add(this.trvCharacters);
            this.frame8.Add(this.GtkAlignment9);
            this.GtkLabel10 = new global::Gtk.Label();
            this.GtkLabel10.Name = "GtkLabel10";
            this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString("Characters");
            this.frame8.LabelWidget = this.GtkLabel10;
            w1.Add(this.frame8);
            global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(w1[this.frame8]));
            w19.Position = 1;
            // Internal child ECMGTK.AddApiKey.ActionArea
            global::Gtk.HButtonBox w20 = this.ActionArea;
            w20.Name = "dialog1_ActionArea";
            w20.Spacing = 10;
            w20.BorderWidth = ((uint)(5));
            w20.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new global::Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Cancel");
            this.AddActionWidget(this.buttonCancel, -6);
            global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w20[this.buttonCancel]));
            w21.Expand = false;
            w21.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button47 = new global::Gtk.Button();
            this.button47.CanFocus = true;
            this.button47.Name = "button47";
            this.button47.UseUnderline = true;
            this.button47.Label = global::Mono.Unix.Catalog.GetString("Import");
            this.AddActionWidget(this.button47, 0);
            global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w20[this.button47]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 580;
            this.label2.MnemonicWidget = this.label2;
            this.Show();
            this.label2.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.NeedKeyClick);
            this.btnRetrieveApi.Clicked += new global::System.EventHandler(this.RetrieveApiInfo);
        }
    }
}
