
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Button button1;
	private global::Gtk.Image image11;
	private global::Gtk.Button button2;
	private global::Gtk.Image image12;
	private global::Gtk.Button button3;
	private global::Gtk.Image image18;
	private global::Gtk.Button button4;
	private global::Gtk.Image image14;
	private global::Gtk.Button button5;
	private global::Gtk.Image image7;
	private global::Gtk.Button button6;
	private global::Gtk.Image image16;
	private global::Gtk.Button button7;
	private global::Gtk.Image image20;
	private global::Gtk.Button button8;
	private global::Gtk.Image image10;
	private global::Gtk.Button button9;
	private global::Gtk.Image image13;
	private global::Gtk.Button button10;
	private global::Gtk.Image image9;
	private global::Gtk.Button button11;
	private global::Gtk.Image image15;
	private global::Gtk.Button button12;
	private global::Gtk.Image image17;
	private global::Gtk.Button button13;
	private global::Gtk.Image image8;
	private global::Gtk.Button button14;
	private global::Gtk.Image image19;
	private global::Gtk.VSeparator vseparator1;
	private global::Gtk.Notebook ntbPages;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 0;
		this.HeightRequest = 532;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		// Container child button1.Gtk.Container+ContainerChild
		this.image11 = new global::Gtk.Image ();
		this.image11.Name = "image11";
		this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Home.png");
		this.button1.Add (this.image11);
		this.button1.Label = null;
		this.vbox2.Add (this.button1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		// Container child button2.Gtk.Container+ContainerChild
		this.image12 = new global::Gtk.Image ();
		this.image12.Name = "image12";
		this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.CharSheet.png");
		this.button2.Add (this.image12);
		this.button2.Label = null;
		this.vbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		// Container child button3.Gtk.Container+ContainerChild
		this.image18 = new global::Gtk.Image ();
		this.image18.Name = "image18";
		this.image18.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Contacts.png");
		this.button3.Add (this.image18);
		this.button3.Label = null;
		this.vbox2.Add (this.button3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button3]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		// Container child button4.Gtk.Container+ContainerChild
		this.image14 = new global::Gtk.Image ();
		this.image14.Name = "image14";
		this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Mail.png");
		this.button4.Add (this.image14);
		this.button4.Label = null;
		this.vbox2.Add (this.button4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button4]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		// Container child button5.Gtk.Container+ContainerChild
		this.image7 = new global::Gtk.Image ();
		this.image7.Name = "image7";
		this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Fitting.png");
		this.button5.Add (this.image7);
		this.button5.Label = null;
		this.vbox2.Add (this.button5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button5]));
		w10.Position = 4;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		// Container child button6.Gtk.Container+ContainerChild
		this.image16 = new global::Gtk.Image ();
		this.image16.Name = "image16";
		this.image16.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Market.png");
		this.button6.Add (this.image16);
		this.button6.Label = null;
		this.vbox2.Add (this.button6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button6]));
		w12.Position = 5;
		w12.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		// Container child button7.Gtk.Container+ContainerChild
		this.image20 = new global::Gtk.Image ();
		this.image20.Name = "image20";
		this.image20.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Research.png");
		this.button7.Add (this.image20);
		this.button7.Label = null;
		this.vbox2.Add (this.button7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button7]));
		w14.Position = 6;
		w14.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		// Container child button8.Gtk.Container+ContainerChild
		this.image10 = new global::Gtk.Image ();
		this.image10.Name = "image10";
		this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Contracts.png");
		this.button8.Add (this.image10);
		this.button8.Label = null;
		this.vbox2.Add (this.button8);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button8]));
		w16.Position = 7;
		w16.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		// Container child button9.Gtk.Container+ContainerChild
		this.image13 = new global::Gtk.Image ();
		this.image13.Name = "image13";
		this.image13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Map.png");
		this.button9.Add (this.image13);
		this.button9.Label = null;
		this.vbox2.Add (this.button9);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button9]));
		w18.Position = 8;
		w18.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button ();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		// Container child button10.Gtk.Container+ContainerChild
		this.image9 = new global::Gtk.Image ();
		this.image9.Name = "image9";
		this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Corps.png");
		this.button10.Add (this.image9);
		this.button10.Label = null;
		this.vbox2.Add (this.button10);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button10]));
		w20.Position = 9;
		w20.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button ();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		// Container child button11.Gtk.Container+ContainerChild
		this.image15 = new global::Gtk.Image ();
		this.image15.Name = "image15";
		this.image15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Assets.png");
		this.button11.Add (this.image15);
		this.button11.Label = null;
		this.vbox2.Add (this.button11);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button11]));
		w22.Position = 10;
		w22.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button12 = new global::Gtk.Button ();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		// Container child button12.Gtk.Container+ContainerChild
		this.image17 = new global::Gtk.Image ();
		this.image17.Name = "image17";
		this.image17.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Money.png");
		this.button12.Add (this.image17);
		this.button12.Label = null;
		this.vbox2.Add (this.button12);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button12]));
		w24.Position = 11;
		w24.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button ();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		// Container child button13.Gtk.Container+ContainerChild
		this.image8 = new global::Gtk.Image ();
		this.image8.Name = "image8";
		this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.Journal.png");
		this.button13.Add (this.image8);
		this.button13.Label = null;
		this.vbox2.Add (this.button13);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button13]));
		w26.Position = 12;
		w26.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		// Container child button14.Gtk.Container+ContainerChild
		this.image19 = new global::Gtk.Image ();
		this.image19.Name = "image19";
		this.image19.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ECMGTK.Resources.News.png");
		this.button14.Add (this.image19);
		this.button14.Label = null;
		this.vbox2.Add (this.button14);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button14]));
		w28.Position = 13;
		w28.Expand = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.hbox1.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ntbPages = new global::Gtk.Notebook ();
		this.ntbPages.CanFocus = true;
		this.ntbPages.Name = "ntbPages";
		this.ntbPages.CurrentPage = 0;
		this.ntbPages.Scrollable = true;
		this.ntbPages.BorderWidth = ((uint)(3));
		// Notebook tab
		global::Gtk.Label w31 = new global::Gtk.Label ();
		w31.Visible = true;
		this.ntbPages.Add (w31);
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
		this.ntbPages.SetTabLabel (w31, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w32 = new global::Gtk.Label ();
		w32.Visible = true;
		this.ntbPages.Add (w32);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.ntbPages.SetTabLabel (w32, this.label4);
		this.label4.ShowAll ();
		this.hbox1.Add (this.ntbPages);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ntbPages]));
		w33.Position = 2;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 532;
		this.button3.Hide ();
		this.button5.Hide ();
		this.button7.Hide ();
		this.button8.Hide ();
		this.button9.Hide ();
		this.button10.Hide ();
		this.button12.Hide ();
		this.button13.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
