
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow {
    private global::Gtk.UIManager UIManager;
    
    private global::Gtk.VBox vbox3;
    
    private global::Gtk.Notebook ntbPages;
    
    private global::Gtk.VBox vbxOverview;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow;
    
    private global::Gtk.VBox vbxAccounts;
    
    private global::Gtk.HSeparator hseparator1;
    
    private global::Gtk.HButtonBox hbuttonbox1;
    
    private global::Gtk.Button btnAddNewApiKey;
    
    private global::Gtk.HBox hbox4;
    
    private global::Gtk.Image image3;
    
    private global::Gtk.Label label5;
    
    private global::Gtk.Button btnCreateNewCharacter;
    
    private global::Gtk.HBox hbox3;
    
    private global::Gtk.Image image2;
    
    private global::Gtk.Label label2;
    
    private global::Gtk.Label label3;
    
    private global::Gtk.VBox vbxCharSheet;
    
    private global::Gtk.HBox hbox5;
    
    private global::Gtk.Frame frame2;
    
    private global::Gtk.Alignment GtkAlignment;
    
    private global::Gtk.Image imgCharPortrait;
    
    private global::Gtk.VBox vbox4;
    
    private global::Gtk.HBox hbox7;
    
    private global::Gtk.Label lblCharName;
    
    private global::Gtk.Table table3;
    
    private global::Gtk.Label label15;
    
    private global::Gtk.Label label16;
    
    private global::Gtk.Label label17;
    
    private global::Gtk.Label label18;
    
    private global::Gtk.Label label21;
    
    private global::Gtk.Label lblAlliance;
    
    private global::Gtk.Label lblAllianceTag;
    
    private global::Gtk.Label lblBackground;
    
    private global::Gtk.Label lblCone;
    
    private global::Gtk.Label lblCorporation;
    
    private global::Gtk.Label lblCorporationTag;
    
    private global::Gtk.Label lblDoB;
    
    private global::Gtk.Label lblSecStatus;
    
    private global::Gtk.Label lblSkillpoints;
    
    private global::Gtk.HSeparator hseparator2;
    
    private global::Gtk.VBox vbox6;
    
    private global::Gtk.HBox hbox8;
    
    private global::Gtk.Button btnRecycleChar;
    
    private global::Gtk.Image image1;
    
    private global::Gtk.Button btnExport;
    
    private global::Gtk.Image image4;
    
    private global::Gtk.HBox hbox6;
    
    private global::Gtk.Notebook ntbCharSheetPages;
    
    private global::Gtk.VBox vbxSkills;
    
    private global::Gtk.HButtonBox hbuttonbox2;
    
    private global::Gtk.Button button103;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private global::Gtk.TreeView trvSkills;
    
    private global::Gtk.Label label7;
    
    private global::Gtk.VBox vbxCertificates;
    
    private global::Gtk.HButtonBox hbuttonbox3;
    
    private global::Gtk.Button button104;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow2;
    
    private global::Gtk.TreeView trvCertificates;
    
    private global::Gtk.Label label8;
    
    private global::Gtk.ScrolledWindow scwMedals;
    
    private global::Gtk.TreeView trvMedals;
    
    private global::Gtk.Label label9;
    
    private global::Gtk.ScrolledWindow scwAttributes;
    
    private global::Gtk.TreeView trvAttributes;
    
    private global::Gtk.Label label10;
    
    private global::Gtk.ScrolledWindow scwImplants;
    
    private global::Gtk.TreeView trvImplants;
    
    private global::Gtk.Label label11;
    
    private global::Gtk.ScrolledWindow scwEmployment;
    
    private global::Gtk.TreeView trvEmployment;
    
    private global::Gtk.Label label12;
    
    private global::Gtk.ScrolledWindow scwStandings;
    
    private global::Gtk.TreeView trvStandings;
    
    private global::Gtk.Label label13;
    
    private global::Gtk.ScrolledWindow scwCombatLogs;
    
    private global::Gtk.TreeView trvKillLogs;
    
    private global::Gtk.Label label14;
    
    private global::Gtk.Label label22;
    
    private global::Gtk.Label label4;
    
    private global::Gtk.Label label23;
    
    private global::Gtk.Label label24;
    
    private global::Gtk.HPaned hpnMarket;
    
    private global::Gtk.Notebook ntbMarketGroups;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow10;
    
    private global::Gtk.TreeView trvMarket;
    
    private global::Gtk.Label label1;
    
    private global::Gtk.VBox vbox8;
    
    private global::Gtk.HBox hbox10;
    
    private global::Gtk.Label label25;
    
    private global::Gtk.Entry txtMarketFilter;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow9;
    
    private global::Gtk.TreeView trvSearchItems;
    
    private global::Gtk.Label label26;
    
    private global::Gtk.Notebook ntbMarketDetails;
    
    private global::Gtk.VBox vbox2;
    
    private global::Gtk.HBox hbox1;
    
    private global::Gtk.Frame frmItemImage;
    
    private global::Gtk.Alignment GtkAlignment1;
    
    private global::Gtk.Button btnShowRender;
    
    private global::Gtk.Image imgItemIconDetails;
    
    private global::Gtk.VBox vbox10;
    
    private global::Gtk.Button btnItemInfo;
    
    private global::Gtk.Image imgItemInfoDetails;
    
    private global::Gtk.VBox vbox9;
    
    private global::Gtk.Label lblItemTreeDetails;
    
    private global::Gtk.Label lblItemNameDetails;
    
    private global::Gtk.VBox vbxBuySell;
    
    private global::Gtk.Label label38;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow13;
    
    private global::Gtk.TreeView trvSellOrders;
    
    private global::Gtk.Label label39;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow14;
    
    private global::Gtk.TreeView trvBuyOrders;
    
    private global::Gtk.Label label35;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow11;
    
    private global::Gtk.VBox vbbMarketGroups;
    
    private global::Gtk.Label label27;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow12;
    
    private global::Gtk.VBox vbbMarketItems;
    
    private global::Gtk.VBox vbox11;
    
    private global::Gtk.Label label28;
    
    private global::Gtk.Label label29;
    
    private global::Gtk.Label label30;
    
    private global::Gtk.Label label31;
    
    private global::Gtk.Label label32;
    
    private global::Gtk.Label label33;
    
    private global::Gtk.Label label34;
    
    private global::Gtk.Label label36;
    
    private global::Gtk.Label label37;
    
    private global::Gtk.Statusbar stbStatus;
    
    protected virtual void Build() {
        global::Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new global::Gtk.UIManager();
        global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = global::Mono.Unix.Catalog.GetString("Eve Character Monitor");
        this.Icon = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.Icons.Corpse.png");
        this.WindowPosition = ((global::Gtk.WindowPosition)(1));
        this.DefaultWidth = 800;
        this.DefaultHeight = 550;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox3 = new global::Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 3;
        // Container child vbox3.Gtk.Box+BoxChild
        this.ntbPages = new global::Gtk.Notebook();
        this.ntbPages.CanFocus = true;
        this.ntbPages.Name = "ntbPages";
        this.ntbPages.CurrentPage = 5;
        this.ntbPages.EnablePopup = true;
        this.ntbPages.TabPos = ((global::Gtk.PositionType)(0));
        this.ntbPages.Scrollable = true;
        this.ntbPages.BorderWidth = ((uint)(3));
        // Container child ntbPages.Gtk.Notebook+NotebookChild
        this.vbxOverview = new global::Gtk.VBox();
        this.vbxOverview.Name = "vbxOverview";
        this.vbxOverview.Spacing = 1;
        this.vbxOverview.BorderWidth = ((uint)(3));
        // Container child vbxOverview.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
        this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
        this.GtkScrolledWindow.BorderWidth = ((uint)(3));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        global::Gtk.Viewport w2 = new global::Gtk.Viewport();
        w2.ShadowType = ((global::Gtk.ShadowType)(0));
        // Container child GtkViewport.Gtk.Container+ContainerChild
        this.vbxAccounts = new global::Gtk.VBox();
        this.vbxAccounts.Name = "vbxAccounts";
        this.vbxAccounts.Spacing = 6;
        this.vbxAccounts.BorderWidth = ((uint)(6));
        w2.Add(this.vbxAccounts);
        this.GtkScrolledWindow.Add(w2);
        this.vbxOverview.Add(this.GtkScrolledWindow);
        global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbxOverview[this.GtkScrolledWindow]));
        w5.Position = 0;
        w5.Padding = ((uint)(2));
        // Container child vbxOverview.Gtk.Box+BoxChild
        this.hseparator1 = new global::Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.vbxOverview.Add(this.hseparator1);
        global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbxOverview[this.hseparator1]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbxOverview.Gtk.Box+BoxChild
        this.hbuttonbox1 = new global::Gtk.HButtonBox();
        this.hbuttonbox1.Name = "hbuttonbox1";
        this.hbuttonbox1.Homogeneous = true;
        this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
        // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.btnAddNewApiKey = new global::Gtk.Button();
        this.btnAddNewApiKey.CanFocus = true;
        this.btnAddNewApiKey.Name = "btnAddNewApiKey";
        // Container child btnAddNewApiKey.Gtk.Container+ContainerChild
        this.hbox4 = new global::Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.image3 = new global::Gtk.Image();
        this.image3.Name = "image3";
        this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.Icons.Internet.png");
        this.hbox4.Add(this.image3);
        global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.image3]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label5 = new global::Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Add New Api Key");
        this.label5.Wrap = true;
        this.label5.SingleLineMode = true;
        this.hbox4.Add(this.label5);
        global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
        w8.Position = 1;
        this.btnAddNewApiKey.Add(this.hbox4);
        this.btnAddNewApiKey.Label = null;
        this.hbuttonbox1.Add(this.btnAddNewApiKey);
        global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnAddNewApiKey]));
        w10.Expand = false;
        w10.Fill = false;
        // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.btnCreateNewCharacter = new global::Gtk.Button();
        this.btnCreateNewCharacter.CanFocus = true;
        this.btnCreateNewCharacter.Name = "btnCreateNewCharacter";
        // Container child btnCreateNewCharacter.Gtk.Container+ContainerChild
        this.hbox3 = new global::Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.image2 = new global::Gtk.Image();
        this.image2.Name = "image2";
        this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.Icons.CustomChar.png");
        this.hbox3.Add(this.image2);
        global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.image2]));
        w11.Position = 0;
        w11.Expand = false;
        w11.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label2 = new global::Gtk.Label();
        this.label2.Name = "label2";
        this.label2.Xalign = 0F;
        this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Create New Character");
        this.label2.Wrap = true;
        this.label2.SingleLineMode = true;
        this.hbox3.Add(this.label2);
        global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
        w12.Position = 1;
        this.btnCreateNewCharacter.Add(this.hbox3);
        this.btnCreateNewCharacter.Label = null;
        this.hbuttonbox1.Add(this.btnCreateNewCharacter);
        global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnCreateNewCharacter]));
        w14.Position = 1;
        w14.Expand = false;
        w14.Fill = false;
        this.vbxOverview.Add(this.hbuttonbox1);
        global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbxOverview[this.hbuttonbox1]));
        w15.Position = 2;
        w15.Expand = false;
        w15.Fill = false;
        this.ntbPages.Add(this.vbxOverview);
        // Notebook tab
        this.label3 = new global::Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Home");
        this.ntbPages.SetTabLabel(this.vbxOverview, this.label3);
        this.label3.ShowAll();
        // Container child ntbPages.Gtk.Notebook+NotebookChild
        this.vbxCharSheet = new global::Gtk.VBox();
        this.vbxCharSheet.Name = "vbxCharSheet";
        this.vbxCharSheet.Spacing = 6;
        // Container child vbxCharSheet.Gtk.Box+BoxChild
        this.hbox5 = new global::Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        this.hbox5.BorderWidth = ((uint)(3));
        // Container child hbox5.Gtk.Box+BoxChild
        this.frame2 = new global::Gtk.Frame();
        this.frame2.Name = "frame2";
        this.frame2.ShadowType = ((global::Gtk.ShadowType)(4));
        // Container child frame2.Gtk.Container+ContainerChild
        this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(1));
        this.GtkAlignment.TopPadding = ((uint)(1));
        this.GtkAlignment.RightPadding = ((uint)(1));
        this.GtkAlignment.BottomPadding = ((uint)(1));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.imgCharPortrait = new global::Gtk.Image();
        this.imgCharPortrait.WidthRequest = 128;
        this.imgCharPortrait.HeightRequest = 128;
        this.imgCharPortrait.Name = "imgCharPortrait";
        this.imgCharPortrait.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.NoPortrait.png");
        this.GtkAlignment.Add(this.imgCharPortrait);
        this.frame2.Add(this.GtkAlignment);
        this.hbox5.Add(this.frame2);
        global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame2]));
        w19.Position = 0;
        w19.Expand = false;
        w19.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.vbox4 = new global::Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 3;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox7 = new global::Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 1;
        // Container child hbox7.Gtk.Box+BoxChild
        this.lblCharName = new global::Gtk.Label();
        this.lblCharName.WidthRequest = 245;
        this.lblCharName.Name = "lblCharName";
        this.lblCharName.Xalign = 0F;
        this.lblCharName.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Character Name</b>");
        this.lblCharName.UseMarkup = true;
        this.hbox7.Add(this.lblCharName);
        global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lblCharName]));
        w20.Position = 0;
        this.vbox4.Add(this.hbox7);
        global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
        w21.Position = 0;
        w21.Expand = false;
        w21.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.table3 = new global::Gtk.Table(((uint)(7)), ((uint)(2)), false);
        this.table3.Name = "table3";
        this.table3.ColumnSpacing = ((uint)(6));
        // Container child table3.Gtk.Table+TableChild
        this.label15 = new global::Gtk.Label();
        this.label15.Name = "label15";
        this.label15.Xalign = 0F;
        this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Skillpoints");
        this.table3.Add(this.label15);
        global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3[this.label15]));
        w22.TopAttach = ((uint)(1));
        w22.BottomAttach = ((uint)(2));
        w22.XOptions = ((global::Gtk.AttachOptions)(4));
        w22.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label16 = new global::Gtk.Label();
        this.label16.Name = "label16";
        this.label16.Xalign = 0F;
        this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Clone");
        this.table3.Add(this.label16);
        global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3[this.label16]));
        w23.TopAttach = ((uint)(2));
        w23.BottomAttach = ((uint)(3));
        w23.XOptions = ((global::Gtk.AttachOptions)(4));
        w23.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label17 = new global::Gtk.Label();
        this.label17.Name = "label17";
        this.label17.Xalign = 0F;
        this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Date of Birth");
        this.table3.Add(this.label17);
        global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3[this.label17]));
        w24.TopAttach = ((uint)(3));
        w24.BottomAttach = ((uint)(4));
        w24.XOptions = ((global::Gtk.AttachOptions)(4));
        w24.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label18 = new global::Gtk.Label();
        this.label18.Name = "label18";
        this.label18.Xalign = 0F;
        this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Background");
        this.table3.Add(this.label18);
        global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3[this.label18]));
        w25.XOptions = ((global::Gtk.AttachOptions)(4));
        w25.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label21 = new global::Gtk.Label();
        this.label21.Name = "label21";
        this.label21.Xalign = 0F;
        this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Security Status");
        this.table3.Add(this.label21);
        global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3[this.label21]));
        w26.TopAttach = ((uint)(6));
        w26.BottomAttach = ((uint)(7));
        w26.XOptions = ((global::Gtk.AttachOptions)(4));
        w26.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblAlliance = new global::Gtk.Label();
        this.lblAlliance.Name = "lblAlliance";
        this.lblAlliance.Xalign = 0F;
        this.lblAlliance.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblAlliance);
        global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3[this.lblAlliance]));
        w27.TopAttach = ((uint)(5));
        w27.BottomAttach = ((uint)(6));
        w27.LeftAttach = ((uint)(1));
        w27.RightAttach = ((uint)(2));
        w27.XOptions = ((global::Gtk.AttachOptions)(4));
        w27.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblAllianceTag = new global::Gtk.Label();
        this.lblAllianceTag.Name = "lblAllianceTag";
        this.lblAllianceTag.Xalign = 0F;
        this.lblAllianceTag.LabelProp = global::Mono.Unix.Catalog.GetString("Alliance");
        this.table3.Add(this.lblAllianceTag);
        global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3[this.lblAllianceTag]));
        w28.TopAttach = ((uint)(5));
        w28.BottomAttach = ((uint)(6));
        w28.XOptions = ((global::Gtk.AttachOptions)(4));
        w28.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblBackground = new global::Gtk.Label();
        this.lblBackground.Name = "lblBackground";
        this.lblBackground.Xalign = 0F;
        this.lblBackground.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblBackground);
        global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3[this.lblBackground]));
        w29.LeftAttach = ((uint)(1));
        w29.RightAttach = ((uint)(2));
        w29.XOptions = ((global::Gtk.AttachOptions)(4));
        w29.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblCone = new global::Gtk.Label();
        this.lblCone.Name = "lblCone";
        this.lblCone.Xalign = 0F;
        this.lblCone.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblCone);
        global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table3[this.lblCone]));
        w30.TopAttach = ((uint)(2));
        w30.BottomAttach = ((uint)(3));
        w30.LeftAttach = ((uint)(1));
        w30.RightAttach = ((uint)(2));
        w30.XOptions = ((global::Gtk.AttachOptions)(4));
        w30.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblCorporation = new global::Gtk.Label();
        this.lblCorporation.Name = "lblCorporation";
        this.lblCorporation.Xalign = 0F;
        this.lblCorporation.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblCorporation);
        global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3[this.lblCorporation]));
        w31.TopAttach = ((uint)(4));
        w31.BottomAttach = ((uint)(5));
        w31.LeftAttach = ((uint)(1));
        w31.RightAttach = ((uint)(2));
        w31.XOptions = ((global::Gtk.AttachOptions)(4));
        w31.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblCorporationTag = new global::Gtk.Label();
        this.lblCorporationTag.Name = "lblCorporationTag";
        this.lblCorporationTag.Xalign = 0F;
        this.lblCorporationTag.LabelProp = global::Mono.Unix.Catalog.GetString("Corporation");
        this.table3.Add(this.lblCorporationTag);
        global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3[this.lblCorporationTag]));
        w32.TopAttach = ((uint)(4));
        w32.BottomAttach = ((uint)(5));
        w32.XOptions = ((global::Gtk.AttachOptions)(4));
        w32.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblDoB = new global::Gtk.Label();
        this.lblDoB.Name = "lblDoB";
        this.lblDoB.Xalign = 0F;
        this.lblDoB.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblDoB);
        global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table3[this.lblDoB]));
        w33.TopAttach = ((uint)(3));
        w33.BottomAttach = ((uint)(4));
        w33.LeftAttach = ((uint)(1));
        w33.RightAttach = ((uint)(2));
        w33.XOptions = ((global::Gtk.AttachOptions)(4));
        w33.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblSecStatus = new global::Gtk.Label();
        this.lblSecStatus.Name = "lblSecStatus";
        this.lblSecStatus.Xalign = 0F;
        this.lblSecStatus.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblSecStatus);
        global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table3[this.lblSecStatus]));
        w34.TopAttach = ((uint)(6));
        w34.BottomAttach = ((uint)(7));
        w34.LeftAttach = ((uint)(1));
        w34.RightAttach = ((uint)(2));
        w34.XOptions = ((global::Gtk.AttachOptions)(4));
        w34.YOptions = ((global::Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.lblSkillpoints = new global::Gtk.Label();
        this.lblSkillpoints.Name = "lblSkillpoints";
        this.lblSkillpoints.Xalign = 0F;
        this.lblSkillpoints.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
        this.table3.Add(this.lblSkillpoints);
        global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table3[this.lblSkillpoints]));
        w35.TopAttach = ((uint)(1));
        w35.BottomAttach = ((uint)(2));
        w35.LeftAttach = ((uint)(1));
        w35.RightAttach = ((uint)(2));
        w35.XOptions = ((global::Gtk.AttachOptions)(4));
        w35.YOptions = ((global::Gtk.AttachOptions)(4));
        this.vbox4.Add(this.table3);
        global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.table3]));
        w36.PackType = ((global::Gtk.PackType)(1));
        w36.Position = 1;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hseparator2 = new global::Gtk.HSeparator();
        this.hseparator2.Name = "hseparator2";
        this.vbox4.Add(this.hseparator2);
        global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
        w37.PackType = ((global::Gtk.PackType)(1));
        w37.Position = 2;
        w37.Expand = false;
        w37.Fill = false;
        this.hbox5.Add(this.vbox4);
        global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox4]));
        w38.Position = 1;
        // Container child hbox5.Gtk.Box+BoxChild
        this.vbox6 = new global::Gtk.VBox();
        this.vbox6.Name = "vbox6";
        this.vbox6.Spacing = 6;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox8 = new global::Gtk.HBox();
        this.hbox8.Name = "hbox8";
        this.hbox8.Spacing = 3;
        // Container child hbox8.Gtk.Box+BoxChild
        this.btnRecycleChar = new global::Gtk.Button();
        this.btnRecycleChar.TooltipMarkup = "Send to Biomass";
        this.btnRecycleChar.CanFocus = true;
        this.btnRecycleChar.Name = "btnRecycleChar";
        this.btnRecycleChar.Relief = ((global::Gtk.ReliefStyle)(2));
        // Container child btnRecycleChar.Gtk.Container+ContainerChild
        this.image1 = new global::Gtk.Image();
        this.image1.Name = "image1";
        this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.Icons.Recycle.png");
        this.btnRecycleChar.Add(this.image1);
        this.btnRecycleChar.Label = null;
        this.hbox8.Add(this.btnRecycleChar);
        global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnRecycleChar]));
        w40.Position = 0;
        w40.Expand = false;
        w40.Fill = false;
        // Container child hbox8.Gtk.Box+BoxChild
        this.btnExport = new global::Gtk.Button();
        this.btnExport.TooltipMarkup = "Export Character";
        this.btnExport.CanFocus = true;
        this.btnExport.Name = "btnExport";
        this.btnExport.Relief = ((global::Gtk.ReliefStyle)(2));
        // Container child btnExport.Gtk.Container+ContainerChild
        this.image4 = new global::Gtk.Image();
        this.image4.Name = "image4";
        this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.Icons.ExportChar.png");
        this.btnExport.Add(this.image4);
        this.btnExport.Label = null;
        this.hbox8.Add(this.btnExport);
        global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnExport]));
        w42.Position = 1;
        w42.Expand = false;
        w42.Fill = false;
        this.vbox6.Add(this.hbox8);
        global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
        w43.Position = 0;
        w43.Expand = false;
        w43.Fill = false;
        this.hbox5.Add(this.vbox6);
        global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox6]));
        w44.PackType = ((global::Gtk.PackType)(1));
        w44.Position = 2;
        w44.Expand = false;
        w44.Fill = false;
        this.vbxCharSheet.Add(this.hbox5);
        global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbxCharSheet[this.hbox5]));
        w45.Position = 0;
        w45.Expand = false;
        w45.Fill = false;
        // Container child vbxCharSheet.Gtk.Box+BoxChild
        this.hbox6 = new global::Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        this.hbox6.BorderWidth = ((uint)(3));
        // Container child hbox6.Gtk.Box+BoxChild
        this.ntbCharSheetPages = new global::Gtk.Notebook();
        this.ntbCharSheetPages.CanFocus = true;
        this.ntbCharSheetPages.Name = "ntbCharSheetPages";
        this.ntbCharSheetPages.CurrentPage = 3;
        this.ntbCharSheetPages.TabPos = ((global::Gtk.PositionType)(0));
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.vbxSkills = new global::Gtk.VBox();
        this.vbxSkills.Name = "vbxSkills";
        // Container child vbxSkills.Gtk.Box+BoxChild
        this.hbuttonbox2 = new global::Gtk.HButtonBox();
        this.hbuttonbox2.Name = "hbuttonbox2";
        this.hbuttonbox2.BorderWidth = ((uint)(3));
        this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
        // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
        this.button103 = new global::Gtk.Button();
        this.button103.CanFocus = true;
        this.button103.Name = "button103";
        this.button103.UseUnderline = true;
        this.button103.Label = global::Mono.Unix.Catalog.GetString("Open Skill Queue");
        this.hbuttonbox2.Add(this.button103);
        global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button103]));
        w46.Expand = false;
        w46.Fill = false;
        this.vbxSkills.Add(this.hbuttonbox2);
        global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbxSkills[this.hbuttonbox2]));
        w47.Position = 0;
        w47.Expand = false;
        w47.Fill = false;
        // Container child vbxSkills.Gtk.Box+BoxChild
        this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.trvSkills = new global::Gtk.TreeView();
        this.trvSkills.CanFocus = true;
        this.trvSkills.Name = "trvSkills";
        this.GtkScrolledWindow1.Add(this.trvSkills);
        this.vbxSkills.Add(this.GtkScrolledWindow1);
        global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbxSkills[this.GtkScrolledWindow1]));
        w49.Position = 1;
        this.ntbCharSheetPages.Add(this.vbxSkills);
        // Notebook tab
        this.label7 = new global::Gtk.Label();
        this.label7.Name = "label7";
        this.label7.Xalign = 0F;
        this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Skills");
        this.ntbCharSheetPages.SetTabLabel(this.vbxSkills, this.label7);
        this.label7.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.vbxCertificates = new global::Gtk.VBox();
        this.vbxCertificates.Name = "vbxCertificates";
        // Container child vbxCertificates.Gtk.Box+BoxChild
        this.hbuttonbox3 = new global::Gtk.HButtonBox();
        this.hbuttonbox3.Name = "hbuttonbox3";
        this.hbuttonbox3.BorderWidth = ((uint)(3));
        this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
        // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
        this.button104 = new global::Gtk.Button();
        this.button104.CanFocus = true;
        this.button104.Name = "button104";
        this.button104.UseUnderline = true;
        this.button104.Label = global::Mono.Unix.Catalog.GetString("Open Certificate Planner");
        this.hbuttonbox3.Add(this.button104);
        global::Gtk.ButtonBox.ButtonBoxChild w51 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.button104]));
        w51.Expand = false;
        w51.Fill = false;
        this.vbxCertificates.Add(this.hbuttonbox3);
        global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbxCertificates[this.hbuttonbox3]));
        w52.Position = 0;
        w52.Expand = false;
        w52.Fill = false;
        // Container child vbxCertificates.Gtk.Box+BoxChild
        this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
        this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
        this.trvCertificates = new global::Gtk.TreeView();
        this.trvCertificates.CanFocus = true;
        this.trvCertificates.Name = "trvCertificates";
        this.GtkScrolledWindow2.Add(this.trvCertificates);
        this.vbxCertificates.Add(this.GtkScrolledWindow2);
        global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbxCertificates[this.GtkScrolledWindow2]));
        w54.Position = 1;
        this.ntbCharSheetPages.Add(this.vbxCertificates);
        global::Gtk.Notebook.NotebookChild w55 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.vbxCertificates]));
        w55.Position = 1;
        // Notebook tab
        this.label8 = new global::Gtk.Label();
        this.label8.Name = "label8";
        this.label8.Xalign = 0F;
        this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Certificates");
        this.ntbCharSheetPages.SetTabLabel(this.vbxCertificates, this.label8);
        this.label8.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.scwMedals = new global::Gtk.ScrolledWindow();
        this.scwMedals.Name = "scwMedals";
        this.scwMedals.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child scwMedals.Gtk.Container+ContainerChild
        this.trvMedals = new global::Gtk.TreeView();
        this.trvMedals.CanFocus = true;
        this.trvMedals.Name = "trvMedals";
        this.scwMedals.Add(this.trvMedals);
        this.ntbCharSheetPages.Add(this.scwMedals);
        global::Gtk.Notebook.NotebookChild w57 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.scwMedals]));
        w57.Position = 2;
        // Notebook tab
        this.label9 = new global::Gtk.Label();
        this.label9.Name = "label9";
        this.label9.Xalign = 0F;
        this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Decorations");
        this.ntbCharSheetPages.SetTabLabel(this.scwMedals, this.label9);
        this.label9.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.scwAttributes = new global::Gtk.ScrolledWindow();
        this.scwAttributes.Name = "scwAttributes";
        this.scwAttributes.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child scwAttributes.Gtk.Container+ContainerChild
        this.trvAttributes = new global::Gtk.TreeView();
        this.trvAttributes.CanFocus = true;
        this.trvAttributes.Name = "trvAttributes";
        this.trvAttributes.EnableSearch = false;
        this.trvAttributes.HeadersVisible = false;
        this.scwAttributes.Add(this.trvAttributes);
        this.ntbCharSheetPages.Add(this.scwAttributes);
        global::Gtk.Notebook.NotebookChild w59 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.scwAttributes]));
        w59.Position = 3;
        // Notebook tab
        this.label10 = new global::Gtk.Label();
        this.label10.Name = "label10";
        this.label10.Xalign = 0F;
        this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Attributes");
        this.ntbCharSheetPages.SetTabLabel(this.scwAttributes, this.label10);
        this.label10.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.scwImplants = new global::Gtk.ScrolledWindow();
        this.scwImplants.Name = "scwImplants";
        this.scwImplants.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child scwImplants.Gtk.Container+ContainerChild
        this.trvImplants = new global::Gtk.TreeView();
        this.trvImplants.CanFocus = true;
        this.trvImplants.Name = "trvImplants";
        this.scwImplants.Add(this.trvImplants);
        this.ntbCharSheetPages.Add(this.scwImplants);
        global::Gtk.Notebook.NotebookChild w61 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.scwImplants]));
        w61.Position = 4;
        // Notebook tab
        this.label11 = new global::Gtk.Label();
        this.label11.Name = "label11";
        this.label11.Xalign = 0F;
        this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Augmentations");
        this.ntbCharSheetPages.SetTabLabel(this.scwImplants, this.label11);
        this.label11.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.scwEmployment = new global::Gtk.ScrolledWindow();
        this.scwEmployment.Name = "scwEmployment";
        this.scwEmployment.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child scwEmployment.Gtk.Container+ContainerChild
        this.trvEmployment = new global::Gtk.TreeView();
        this.trvEmployment.CanFocus = true;
        this.trvEmployment.Name = "trvEmployment";
        this.scwEmployment.Add(this.trvEmployment);
        this.ntbCharSheetPages.Add(this.scwEmployment);
        global::Gtk.Notebook.NotebookChild w63 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.scwEmployment]));
        w63.Position = 5;
        // Notebook tab
        this.label12 = new global::Gtk.Label();
        this.label12.Name = "label12";
        this.label12.Xalign = 0F;
        this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Employment History");
        this.ntbCharSheetPages.SetTabLabel(this.scwEmployment, this.label12);
        this.label12.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.scwStandings = new global::Gtk.ScrolledWindow();
        this.scwStandings.Name = "scwStandings";
        this.scwStandings.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child scwStandings.Gtk.Container+ContainerChild
        this.trvStandings = new global::Gtk.TreeView();
        this.trvStandings.CanFocus = true;
        this.trvStandings.Name = "trvStandings";
        this.scwStandings.Add(this.trvStandings);
        this.ntbCharSheetPages.Add(this.scwStandings);
        global::Gtk.Notebook.NotebookChild w65 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.scwStandings]));
        w65.Position = 6;
        // Notebook tab
        this.label13 = new global::Gtk.Label();
        this.label13.Name = "label13";
        this.label13.Xalign = 0F;
        this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Standings");
        this.ntbCharSheetPages.SetTabLabel(this.scwStandings, this.label13);
        this.label13.ShowAll();
        // Container child ntbCharSheetPages.Gtk.Notebook+NotebookChild
        this.scwCombatLogs = new global::Gtk.ScrolledWindow();
        this.scwCombatLogs.Name = "scwCombatLogs";
        this.scwCombatLogs.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child scwCombatLogs.Gtk.Container+ContainerChild
        this.trvKillLogs = new global::Gtk.TreeView();
        this.trvKillLogs.CanFocus = true;
        this.trvKillLogs.Name = "trvKillLogs";
        this.scwCombatLogs.Add(this.trvKillLogs);
        this.ntbCharSheetPages.Add(this.scwCombatLogs);
        global::Gtk.Notebook.NotebookChild w67 = ((global::Gtk.Notebook.NotebookChild)(this.ntbCharSheetPages[this.scwCombatLogs]));
        w67.Position = 7;
        // Notebook tab
        this.label14 = new global::Gtk.Label();
        this.label14.WidthRequest = 128;
        this.label14.HeightRequest = 32;
        this.label14.Name = "label14";
        this.label14.Xalign = 0F;
        this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Combat Log");
        this.ntbCharSheetPages.SetTabLabel(this.scwCombatLogs, this.label14);
        this.label14.ShowAll();
        this.hbox6.Add(this.ntbCharSheetPages);
        global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.ntbCharSheetPages]));
        w68.Position = 0;
        this.vbxCharSheet.Add(this.hbox6);
        global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbxCharSheet[this.hbox6]));
        w69.Position = 1;
        this.ntbPages.Add(this.vbxCharSheet);
        global::Gtk.Notebook.NotebookChild w70 = ((global::Gtk.Notebook.NotebookChild)(this.ntbPages[this.vbxCharSheet]));
        w70.Position = 1;
        // Notebook tab
        this.label22 = new global::Gtk.Label();
        this.label22.Name = "label22";
        this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Character Sheet");
        this.ntbPages.SetTabLabel(this.vbxCharSheet, this.label22);
        this.label22.ShowAll();
        // Notebook tab
        global::Gtk.Label w71 = new global::Gtk.Label();
        w71.Visible = true;
        this.ntbPages.Add(w71);
        this.label4 = new global::Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("People & Places");
        this.ntbPages.SetTabLabel(w71, this.label4);
        this.label4.ShowAll();
        // Notebook tab
        global::Gtk.Label w72 = new global::Gtk.Label();
        w72.Visible = true;
        this.ntbPages.Add(w72);
        this.label23 = new global::Gtk.Label();
        this.label23.Name = "label23";
        this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Mail");
        this.ntbPages.SetTabLabel(w72, this.label23);
        this.label23.ShowAll();
        // Notebook tab
        global::Gtk.Label w73 = new global::Gtk.Label();
        w73.Visible = true;
        this.ntbPages.Add(w73);
        this.label24 = new global::Gtk.Label();
        this.label24.Name = "label24";
        this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Fittings");
        this.ntbPages.SetTabLabel(w73, this.label24);
        this.label24.ShowAll();
        // Container child ntbPages.Gtk.Notebook+NotebookChild
        this.hpnMarket = new global::Gtk.HPaned();
        this.hpnMarket.CanFocus = true;
        this.hpnMarket.Name = "hpnMarket";
        this.hpnMarket.Position = 215;
        this.hpnMarket.BorderWidth = ((uint)(3));
        // Container child hpnMarket.Gtk.Paned+PanedChild
        this.ntbMarketGroups = new global::Gtk.Notebook();
        this.ntbMarketGroups.CanFocus = true;
        this.ntbMarketGroups.Name = "ntbMarketGroups";
        this.ntbMarketGroups.CurrentPage = 0;
        this.ntbMarketGroups.ShowBorder = false;
        this.ntbMarketGroups.BorderWidth = ((uint)(1));
        // Container child ntbMarketGroups.Gtk.Notebook+NotebookChild
        this.GtkScrolledWindow10 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow10.Name = "GtkScrolledWindow10";
        this.GtkScrolledWindow10.BorderWidth = ((uint)(3));
        // Container child GtkScrolledWindow10.Gtk.Container+ContainerChild
        this.trvMarket = new global::Gtk.TreeView();
        this.trvMarket.CanFocus = true;
        this.trvMarket.Name = "trvMarket";
        this.trvMarket.HeadersVisible = false;
        this.GtkScrolledWindow10.Add(this.trvMarket);
        this.ntbMarketGroups.Add(this.GtkScrolledWindow10);
        // Notebook tab
        this.label1 = new global::Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Market");
        this.ntbMarketGroups.SetTabLabel(this.GtkScrolledWindow10, this.label1);
        this.label1.ShowAll();
        // Container child ntbMarketGroups.Gtk.Notebook+NotebookChild
        this.vbox8 = new global::Gtk.VBox();
        this.vbox8.Name = "vbox8";
        this.vbox8.Spacing = 6;
        this.vbox8.BorderWidth = ((uint)(3));
        // Container child vbox8.Gtk.Box+BoxChild
        this.hbox10 = new global::Gtk.HBox();
        this.hbox10.Name = "hbox10";
        this.hbox10.Spacing = 6;
        // Container child hbox10.Gtk.Box+BoxChild
        this.label25 = new global::Gtk.Label();
        this.label25.Name = "label25";
        this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Search:");
        this.hbox10.Add(this.label25);
        global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label25]));
        w76.Position = 0;
        w76.Expand = false;
        w76.Fill = false;
        // Container child hbox10.Gtk.Box+BoxChild
        this.txtMarketFilter = new global::Gtk.Entry();
        this.txtMarketFilter.CanFocus = true;
        this.txtMarketFilter.Name = "txtMarketFilter";
        this.txtMarketFilter.IsEditable = true;
        this.txtMarketFilter.InvisibleChar = '●';
        this.hbox10.Add(this.txtMarketFilter);
        global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.txtMarketFilter]));
        w77.Position = 1;
        this.vbox8.Add(this.hbox10);
        global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox10]));
        w78.Position = 0;
        w78.Expand = false;
        w78.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.GtkScrolledWindow9 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow9.Name = "GtkScrolledWindow9";
        this.GtkScrolledWindow9.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow9.Gtk.Container+ContainerChild
        this.trvSearchItems = new global::Gtk.TreeView();
        this.trvSearchItems.CanFocus = true;
        this.trvSearchItems.Name = "trvSearchItems";
        this.trvSearchItems.HeadersVisible = false;
        this.GtkScrolledWindow9.Add(this.trvSearchItems);
        this.vbox8.Add(this.GtkScrolledWindow9);
        global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow9]));
        w80.Position = 1;
        this.ntbMarketGroups.Add(this.vbox8);
        global::Gtk.Notebook.NotebookChild w81 = ((global::Gtk.Notebook.NotebookChild)(this.ntbMarketGroups[this.vbox8]));
        w81.Position = 1;
        // Notebook tab
        this.label26 = new global::Gtk.Label();
        this.label26.Name = "label26";
        this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Search");
        this.ntbMarketGroups.SetTabLabel(this.vbox8, this.label26);
        this.label26.ShowAll();
        this.hpnMarket.Add(this.ntbMarketGroups);
        global::Gtk.Paned.PanedChild w82 = ((global::Gtk.Paned.PanedChild)(this.hpnMarket[this.ntbMarketGroups]));
        w82.Resize = false;
        // Container child hpnMarket.Gtk.Paned+PanedChild
        this.ntbMarketDetails = new global::Gtk.Notebook();
        this.ntbMarketDetails.CanFocus = true;
        this.ntbMarketDetails.Name = "ntbMarketDetails";
        this.ntbMarketDetails.CurrentPage = 0;
        this.ntbMarketDetails.BorderWidth = ((uint)(3));
        // Container child ntbMarketDetails.Gtk.Notebook+NotebookChild
        this.vbox2 = new global::Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 20;
        this.vbox2.BorderWidth = ((uint)(3));
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox1 = new global::Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 1;
        this.hbox1.BorderWidth = ((uint)(1));
        // Container child hbox1.Gtk.Box+BoxChild
        this.frmItemImage = new global::Gtk.Frame();
        this.frmItemImage.Name = "frmItemImage";
        this.frmItemImage.ShadowType = ((global::Gtk.ShadowType)(0));
        // Container child frmItemImage.Gtk.Container+ContainerChild
        this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment1.Name = "GtkAlignment1";
        // Container child GtkAlignment1.Gtk.Container+ContainerChild
        this.btnShowRender = new global::Gtk.Button();
        this.btnShowRender.CanFocus = true;
        this.btnShowRender.Name = "btnShowRender";
        this.btnShowRender.Relief = ((global::Gtk.ReliefStyle)(2));
        // Container child btnShowRender.Gtk.Container+ContainerChild
        this.imgItemIconDetails = new global::Gtk.Image();
        this.imgItemIconDetails.WidthRequest = 64;
        this.imgItemIconDetails.HeightRequest = 64;
        this.imgItemIconDetails.Name = "imgItemIconDetails";
        this.btnShowRender.Add(this.imgItemIconDetails);
        this.btnShowRender.Label = null;
        this.GtkAlignment1.Add(this.btnShowRender);
        this.frmItemImage.Add(this.GtkAlignment1);
        this.hbox1.Add(this.frmItemImage);
        global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frmItemImage]));
        w86.Position = 0;
        w86.Expand = false;
        w86.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbox10 = new global::Gtk.VBox();
        this.vbox10.Name = "vbox10";
        this.vbox10.Spacing = 6;
        // Container child vbox10.Gtk.Box+BoxChild
        this.btnItemInfo = new global::Gtk.Button();
        this.btnItemInfo.CanFocus = true;
        this.btnItemInfo.Name = "btnItemInfo";
        this.btnItemInfo.Relief = ((global::Gtk.ReliefStyle)(2));
        this.btnItemInfo.Xalign = 0F;
        this.btnItemInfo.Yalign = 0F;
        // Container child btnItemInfo.Gtk.Container+ContainerChild
        this.imgItemInfoDetails = new global::Gtk.Image();
        this.imgItemInfoDetails.WidthRequest = 16;
        this.imgItemInfoDetails.HeightRequest = 16;
        this.imgItemInfoDetails.Name = "imgItemInfoDetails";
        this.imgItemInfoDetails.Xalign = 0F;
        this.imgItemInfoDetails.Yalign = 0F;
        this.imgItemInfoDetails.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ECMGTK.Resources.Icons.Info16.png");
        this.btnItemInfo.Add(this.imgItemInfoDetails);
        this.btnItemInfo.Label = null;
        this.vbox10.Add(this.btnItemInfo);
        global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.btnItemInfo]));
        w88.Position = 0;
        w88.Expand = false;
        w88.Fill = false;
        this.hbox1.Add(this.vbox10);
        global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox10]));
        w89.Position = 1;
        w89.Expand = false;
        w89.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbox9 = new global::Gtk.VBox();
        this.vbox9.Name = "vbox9";
        this.vbox9.Spacing = 6;
        // Container child vbox9.Gtk.Box+BoxChild
        this.lblItemTreeDetails = new global::Gtk.Label();
        this.lblItemTreeDetails.Name = "lblItemTreeDetails";
        this.lblItemTreeDetails.Xalign = 0F;
        this.lblItemTreeDetails.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
        this.vbox9.Add(this.lblItemTreeDetails);
        global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.lblItemTreeDetails]));
        w90.Position = 0;
        w90.Expand = false;
        w90.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.lblItemNameDetails = new global::Gtk.Label();
        this.lblItemNameDetails.Name = "lblItemNameDetails";
        this.lblItemNameDetails.Xalign = 0F;
        this.lblItemNameDetails.LabelProp = global::Mono.Unix.Catalog.GetString("<b>No Type Selected</b>");
        this.lblItemNameDetails.UseMarkup = true;
        this.vbox9.Add(this.lblItemNameDetails);
        global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.lblItemNameDetails]));
        w91.Position = 1;
        w91.Expand = false;
        w91.Fill = false;
        this.hbox1.Add(this.vbox9);
        global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox9]));
        w92.Position = 2;
        w92.Expand = false;
        w92.Fill = false;
        this.vbox2.Add(this.hbox1);
        global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
        w93.Position = 0;
        w93.Expand = false;
        w93.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.vbxBuySell = new global::Gtk.VBox();
        this.vbxBuySell.Name = "vbxBuySell";
        this.vbxBuySell.Spacing = 6;
        this.vbxBuySell.BorderWidth = ((uint)(3));
        // Container child vbxBuySell.Gtk.Box+BoxChild
        this.label38 = new global::Gtk.Label();
        this.label38.Name = "label38";
        this.label38.Xalign = 0F;
        this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("Sellers");
        this.vbxBuySell.Add(this.label38);
        global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbxBuySell[this.label38]));
        w94.Position = 0;
        w94.Expand = false;
        w94.Fill = false;
        // Container child vbxBuySell.Gtk.Box+BoxChild
        this.GtkScrolledWindow13 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow13.Name = "GtkScrolledWindow13";
        this.GtkScrolledWindow13.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow13.Gtk.Container+ContainerChild
        this.trvSellOrders = new global::Gtk.TreeView();
        this.trvSellOrders.CanFocus = true;
        this.trvSellOrders.Name = "trvSellOrders";
        this.GtkScrolledWindow13.Add(this.trvSellOrders);
        this.vbxBuySell.Add(this.GtkScrolledWindow13);
        global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbxBuySell[this.GtkScrolledWindow13]));
        w96.Position = 1;
        // Container child vbxBuySell.Gtk.Box+BoxChild
        this.label39 = new global::Gtk.Label();
        this.label39.Name = "label39";
        this.label39.Xalign = 0F;
        this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("Buyers");
        this.vbxBuySell.Add(this.label39);
        global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbxBuySell[this.label39]));
        w97.Position = 2;
        w97.Expand = false;
        w97.Fill = false;
        // Container child vbxBuySell.Gtk.Box+BoxChild
        this.GtkScrolledWindow14 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow14.Name = "GtkScrolledWindow14";
        this.GtkScrolledWindow14.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow14.Gtk.Container+ContainerChild
        this.trvBuyOrders = new global::Gtk.TreeView();
        this.trvBuyOrders.CanFocus = true;
        this.trvBuyOrders.Name = "trvBuyOrders";
        this.GtkScrolledWindow14.Add(this.trvBuyOrders);
        this.vbxBuySell.Add(this.GtkScrolledWindow14);
        global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbxBuySell[this.GtkScrolledWindow14]));
        w99.PackType = ((global::Gtk.PackType)(1));
        w99.Position = 3;
        this.vbox2.Add(this.vbxBuySell);
        global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbxBuySell]));
        w100.Position = 1;
        this.ntbMarketDetails.Add(this.vbox2);
        // Notebook tab
        this.label35 = new global::Gtk.Label();
        this.label35.Name = "label35";
        this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("Details");
        this.ntbMarketDetails.SetTabLabel(this.vbox2, this.label35);
        this.label35.ShowAll();
        // Container child ntbMarketDetails.Gtk.Notebook+NotebookChild
        this.GtkScrolledWindow11 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow11.Name = "GtkScrolledWindow11";
        this.GtkScrolledWindow11.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
        this.GtkScrolledWindow11.ShadowType = ((global::Gtk.ShadowType)(1));
        this.GtkScrolledWindow11.BorderWidth = ((uint)(3));
        // Container child GtkScrolledWindow11.Gtk.Container+ContainerChild
        global::Gtk.Viewport w102 = new global::Gtk.Viewport();
        w102.ShadowType = ((global::Gtk.ShadowType)(0));
        // Container child GtkViewport1.Gtk.Container+ContainerChild
        this.vbbMarketGroups = new global::Gtk.VBox();
        this.vbbMarketGroups.Name = "vbbMarketGroups";
        this.vbbMarketGroups.Spacing = 3;
        this.vbbMarketGroups.BorderWidth = ((uint)(3));
        w102.Add(this.vbbMarketGroups);
        this.GtkScrolledWindow11.Add(w102);
        this.ntbMarketDetails.Add(this.GtkScrolledWindow11);
        global::Gtk.Notebook.NotebookChild w105 = ((global::Gtk.Notebook.NotebookChild)(this.ntbMarketDetails[this.GtkScrolledWindow11]));
        w105.Position = 1;
        // Notebook tab
        this.label27 = new global::Gtk.Label();
        this.label27.Name = "label27";
        this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Groups");
        this.ntbMarketDetails.SetTabLabel(this.GtkScrolledWindow11, this.label27);
        this.label27.ShowAll();
        // Container child ntbMarketDetails.Gtk.Notebook+NotebookChild
        this.GtkScrolledWindow12 = new global::Gtk.ScrolledWindow();
        this.GtkScrolledWindow12.Name = "GtkScrolledWindow12";
        this.GtkScrolledWindow12.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow12.Gtk.Container+ContainerChild
        global::Gtk.Viewport w106 = new global::Gtk.Viewport();
        w106.ShadowType = ((global::Gtk.ShadowType)(0));
        // Container child GtkViewport2.Gtk.Container+ContainerChild
        this.vbbMarketItems = new global::Gtk.VBox();
        this.vbbMarketItems.Name = "vbbMarketItems";
        // Container child vbbMarketItems.Gtk.Box+BoxChild
        this.vbox11 = new global::Gtk.VBox();
        this.vbox11.Name = "vbox11";
        this.vbox11.Spacing = 6;
        this.vbbMarketItems.Add(this.vbox11);
        global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbbMarketItems[this.vbox11]));
        w107.Position = 0;
        w106.Add(this.vbbMarketItems);
        this.GtkScrolledWindow12.Add(w106);
        this.ntbMarketDetails.Add(this.GtkScrolledWindow12);
        global::Gtk.Notebook.NotebookChild w110 = ((global::Gtk.Notebook.NotebookChild)(this.ntbMarketDetails[this.GtkScrolledWindow12]));
        w110.Position = 2;
        // Notebook tab
        this.label28 = new global::Gtk.Label();
        this.label28.Name = "label28";
        this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("My Orders");
        this.ntbMarketDetails.SetTabLabel(this.GtkScrolledWindow12, this.label28);
        this.label28.ShowAll();
        this.hpnMarket.Add(this.ntbMarketDetails);
        this.ntbPages.Add(this.hpnMarket);
        global::Gtk.Notebook.NotebookChild w112 = ((global::Gtk.Notebook.NotebookChild)(this.ntbPages[this.hpnMarket]));
        w112.Position = 5;
        // Notebook tab
        this.label29 = new global::Gtk.Label();
        this.label29.Name = "label29";
        this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Market");
        this.ntbPages.SetTabLabel(this.hpnMarket, this.label29);
        this.label29.ShowAll();
        // Notebook tab
        global::Gtk.Label w113 = new global::Gtk.Label();
        w113.Visible = true;
        this.ntbPages.Add(w113);
        this.label30 = new global::Gtk.Label();
        this.label30.Name = "label30";
        this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Science & Industry");
        this.ntbPages.SetTabLabel(w113, this.label30);
        this.label30.ShowAll();
        // Notebook tab
        global::Gtk.Label w114 = new global::Gtk.Label();
        w114.Visible = true;
        this.ntbPages.Add(w114);
        this.label31 = new global::Gtk.Label();
        this.label31.Name = "label31";
        this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Contracts");
        this.ntbPages.SetTabLabel(w114, this.label31);
        this.label31.ShowAll();
        // Notebook tab
        global::Gtk.Label w115 = new global::Gtk.Label();
        w115.Visible = true;
        this.ntbPages.Add(w115);
        this.label32 = new global::Gtk.Label();
        this.label32.Name = "label32";
        this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("Map");
        this.ntbPages.SetTabLabel(w115, this.label32);
        this.label32.ShowAll();
        // Notebook tab
        global::Gtk.Label w116 = new global::Gtk.Label();
        w116.Visible = true;
        this.ntbPages.Add(w116);
        this.label33 = new global::Gtk.Label();
        this.label33.Name = "label33";
        this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("Corporations");
        this.ntbPages.SetTabLabel(w116, this.label33);
        this.label33.ShowAll();
        // Notebook tab
        global::Gtk.Label w117 = new global::Gtk.Label();
        w117.Visible = true;
        this.ntbPages.Add(w117);
        this.label34 = new global::Gtk.Label();
        this.label34.Name = "label34";
        this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("Assets");
        this.ntbPages.SetTabLabel(w117, this.label34);
        this.label34.ShowAll();
        // Notebook tab
        global::Gtk.Label w118 = new global::Gtk.Label();
        w118.Visible = true;
        this.ntbPages.Add(w118);
        this.label36 = new global::Gtk.Label();
        this.label36.Name = "label36";
        this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("Money");
        this.ntbPages.SetTabLabel(w118, this.label36);
        this.label36.ShowAll();
        // Notebook tab
        global::Gtk.Label w119 = new global::Gtk.Label();
        w119.Visible = true;
        this.ntbPages.Add(w119);
        this.label37 = new global::Gtk.Label();
        this.label37.Name = "label37";
        this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("Help And Settings");
        this.ntbPages.SetTabLabel(w119, this.label37);
        this.label37.ShowAll();
        this.vbox3.Add(this.ntbPages);
        global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.ntbPages]));
        w120.Position = 0;
        // Container child vbox3.Gtk.Box+BoxChild
        this.stbStatus = new global::Gtk.Statusbar();
        this.stbStatus.Name = "stbStatus";
        this.stbStatus.Spacing = 6;
        this.stbStatus.BorderWidth = ((uint)(3));
        this.stbStatus.HasResizeGrip = false;
        this.vbox3.Add(this.stbStatus);
        global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.stbStatus]));
        w121.Position = 1;
        w121.Expand = false;
        w121.Fill = false;
        this.Add(this.vbox3);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.imgItemIconDetails.Hide();
        this.btnItemInfo.Hide();
        this.lblItemTreeDetails.Hide();
        this.vbxBuySell.Hide();
        this.Hide();
        this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.btnAddNewApiKey.Clicked += new global::System.EventHandler(this.AddNewKey);
        this.trvAttributes.RowActivated += new global::Gtk.RowActivatedHandler(this.ClearSelection);
        this.trvMarket.RowCollapsed += new global::Gtk.RowCollapsedHandler(this.RowCollapsed);
        this.trvMarket.RowActivated += new global::Gtk.RowActivatedHandler(this.RowActivated);
        this.txtMarketFilter.Changed += new global::System.EventHandler(this.SearchTextChanged);
        this.trvSearchItems.RowCollapsed += new global::Gtk.RowCollapsedHandler(this.RowCollapsed);
        this.trvSearchItems.RowActivated += new global::Gtk.RowActivatedHandler(this.RowActivated);
        this.btnShowRender.Clicked += new global::System.EventHandler(this.ShowItemRender);
    }
}
